version: '3.8'  # Версія формату docker-compose

services:  # Список сервісів (контейнерів), які будуть запущені
  bot:  # Назва сервісу
    image: proposals_band
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proposals_band
    volumes:
      - .:/app/
    restart: unless-stopped


